SELECT COUNT(*) AS QTDE_REGISTROS,
       AVG(TOTAL) AS MEDIA,
       ROUND(AVG(TOTAL), 2) AS MEDIA,
       MAX(TOTAL) AS MAXIMO,
       MIN(TOTAL) AS MINIMO,
       SUM(TOTAL) AS SOMA,
       MAX(DATA) AS DATA_MAIOR,
       MIN(DATA) AS DATA_MENOR
FROM TCONTRATO;

SELECT MAX(COD_CONTRATO) + 1 AS PROXIMO_CODIGO
FROM TCONTRATO;

SELECT * FROM TALUNO;

SELECT * FROM TCONTRATO;

SELECT COD_ALUNO, 
       COUNT(*) AS QTDE_CONTRATO,
       SUM(TOTAL) AS VALOR_TOTAL
FROM TCONTRATO
GROUP BY COD_ALUNO;

SELECT SYSDATE FROM DUAL;

SELECT TO_CHAR(TRUNC(DATA), 
       

