CREATE SEQUENCE SEQ_ALUNO1
START WITH 60
INCREMENT BY 2
MINVALUE 60
MAXVALUE 100
NOCACHE
NOCYCLE;

INSERT INTO TALUNO (COD_ALUNO, NOME)
VALUES (SEQ_ALUNO1.NEXTVAL, 'MASTER TRAINING 2');

SELECT * FROM TALUNO
ORDER BY COD_ALUNO;

COMMIT;

SELECT * FROM USER_SEQUENCES
ORDER BY SEQUENCE_NAME;

SELECT SEQ_ALUNO1.CURRVAL FROM DUAL;

ALTER SEQUENCE SEQ_ALUNO1 MAXVALUE 500;

DROP SEQUENCE SEQ_ALUNO1;

CREATE SEQUENCE SEQ_ALUNO1 START WITH 80;

SELECT NOME FROM TALUNO 
WHERE NOME LIKE '%A%';

CREATE INDEX IND_TALUNO_NOME ON TALUNO(NOME);

SELECT NOME FROM TALUNO
WHERE NOME LIKE '%MA%';

CREATE INDEX IND_TALU_NOMECIDADE
ON TALUNO(NOME, CIDADE);

SELECT NOME, CIDADE FROM TALUNO 
WHERE NOME LIKE '%A%' AND CIDADE LIKE '%A%';

SELECT * FROM USER_INDEXES;

DROP INDEX IND_TALU_NOMECIDADE;

CREATE SYNONYM ALU FOR TALUNO;

SELECT * FROM ALU;







