CREATE OR REPLACE PACKAGE PCKG_ALUNO
IS
  vCidade VARCHAR2(30);
  vMedia NUMBER(8, 2);
  vNome VARCHAR2(30);
  PROCEDURE DELETA_ALUNO(pCod_Aluno NUMBER);
  PROCEDURE MEDIA_CONTRATOS;
  PROCEDURE CON_ALUNO(pCod_Aluno NUMBER);
END;

CREATE OR REPLACE PACKAGE BODY PCKG_ALUNO
IS

 vTESTE VARCHAR2(20);
 
 PROCEDURE MEDIA_CONTRATOS
 IS
 BEGIN
   vTeste := 'teste';
   SELECT AVG(TOTAL) INTO vMEDIA FROM TCONTRATO;
 END;
 
 PROCEDURE CON_ALUNO(pCOD_ALUNO NUMBER)
 IS
 BEGIN
   vNOME := '';
   SELECT NOME INTO vNOME FROM TALUNO
   WHERE COD_ALUNO = pCOD_ALUNO;
 EXCEPTION
   WHEN No_Data_Found THEN
     Dbms_Output.Put_Line('Aluno não existe');
 END;
 
 PROCEDURE DELETA_ALUNO(pCOD_ALUNO NUMBER)
 IS
 BEGIN
   CON_ALUNO(pCOD_ALUNO);
   IF LENGTH(vNome) > 0 THEN
     DELETE FROM TALUNO WHERE COD_ALUNO = pCOD_ALUNO;
     Dbms_Output.Put_Line(vNOME || '-> Excluído');
   END IF;
 END;

END;

EXEC PCKG_ALUNO.DELETA_ALUNO(99);

SELECT * FROM TALUNO;

DECLARE
  m NUMBER;
BEGIN
  PCKG_ALUNO.MEDIA_CONTRATOS;
  m := PCKG_ALUNO.vMedia;
  Dbms_Output.Put_Line('Média: ' || m);
END;

BEGIN
  PCKG_ALUNO.CON_ALUNO(2);
  Dbms_Output.Put_Line('Nome ' || PCKG_ALUNO.vNome);
END;