SELECT COD_ALUNO, TRUNC(DATA) DATA,
       SUM(DESCONTO) DESCONTO,
       SUM(TOTAL) TOTAL
FROM TCONTRATO
GROUP BY ROLLUP(COD_ALUNO, TRUNC(DATA));

SELECT COD_ALUNO,
       CASE
         WHEN TRUNC(DATA) IS NULL AND COD_ALUNO IS NOT NULL THEN 'SUB-TOTAL'
         WHEN COD_ALUNO IS NULL THEN 'TOTAL'
         ELSE TO_CHAR( TRUNC(DATA) )
       END DESCRICAO,
       ROUND(AVG(DESCONTO),2) DESCONTO,
       SUM(TOTAL) TOTAL
FROM TCONTRATO
GROUP BY ROLLUP( COD_ALUNO, TRUNC(DATA) );

SELECT COD_ALUNO,
       TRUNC(DATA),
       SUM(TOTAL)
FROM TCONTRATO
GROUP BY CUBE(COD_ALUNO, TRUNC(DATA));

SELECT * FROM TCONTRATO;

SELECT GROUPING(COD_ALUNO), SUM(TOTAL)
FROM TCONTRATO 
GROUP BY ROLLUP(COD_ALUNO);

SELECT GROUPING(COD_ALUNO),
       CASE
         WHEN GROUPING(COD_ALUNO)=0 THEN TO_CHAR(COD_ALUNO)
         ELSE 'Total Geral:'
       END ALUNO,
       SUM(TOTAL)
FROM TCONTRATO
GROUP BY ROLLUP(COD_ALUNO);

SELECT TRUNC(DATA),
       GROUPING_ID(TRUNC(DATA)) GDT,
       COD_ALUNO,
       GROUPING_ID(COD_ALUNO) GCL,
       SUM(TOTAL)
FROM TCONTRATO
GROUP BY ROLLUP (TRUNC(DATA), COD_ALUNO);

SELECT TRUNC(DATA) DATA, COD_ALUNO, 
    CASE 
     WHEN GROUPING_ID(COD_ALUNO) = 1 AND
        GROUPING_ID(TRUNC(DATA)) = 0 THEN 'Total do Dia: '
     WHEN GROUPING_ID(COD_ALUNO) = 1 AND
        GROUPING_ID(TRUNC(DATA)) = 1 THEN 'Total Geral : '
    END AS DESCRICAO,
    SUM(TOTAL) TOTAL
FROM TCONTRATO
GROUP BY ROLLUP(TRUNC(DATA), COD_ALUNO);

SELECT COD_ALUNO, TRUNC(DATA), SUM(TOTAL)
FROM TCONTRATO
GROUP BY GROUPING SETS (COD_ALUNO, TRUNC(DATA));

SELECT TRUNC(DATA), COD_ALUNO, SUM(TOTAL),
       RANK() OVER (ORDER BY SUM(TOTAL) DESC) POSICAO
FROM TCONTRATO
GROUP BY (TRUNC(DATA), COD_ALUNO);

SELECT COD_ALUNO, SUM(TOTAL),
       RANK() OVER (ORDER BY SUM(TOTAL) DESC) POSICAO
FROM TCONTRATO
GROUP BY (COD_ALUNO);

SELECT TRUNC(DATA), COD_ALUNO, SUM(TOTAL),
       RANK() OVER (PARTITION BY TRUNC(DATA)
        ORDER BY SUM(TOTAL) DESC) POSICAO
FROM TCONTRATO
GROUP BY (TRUNC(DATA), COD_ALUNO)
ORDER BY TRUNC(DATA);

SELECT COD_CONTRATO, TOTAL, 
     RANK() OVER (ORDER BY TOTAL DESC) "RANK()",
     DENSE_RANK() OVER (ORDER BY TOTAL DESC) "DENSE_RANK()"
FROM TCONTRATO
GROUP BY COD_CONTRATO, TOTAL;

SELECT COD_ALUNO, SUM(TOTAL) "Total do Cliente", 
    ROUND(RATIO_TO_REPORT(SUM(TOTAL)) OVER()*100,2) "% do Total"
FROM TCONTRATO
GROUP BY COD_ALUNO;

SELECT COD_ALUNO,
       TRUNC(DATA),
       SUM(TOTAL) "Total do Dia",
       ROUND(RATIO_TO_REPORT(SUM(TOTAL)) OVER(PARTITION BY
       TRUNC(DATA)) * 100, 2) "% do Dia"
FROM TCONTRATO
GROUP BY COD_ALUNO, TRUNC(DATA)
ORDER BY 2 ASC, COD_ALUNO;

SELECT TRUNC(DATA), SUM(TOTAL) total_dia,
  LAG (SUM(TOTAL),1) OVER (ORDER BY TRUNC(DATA)) anterior,
  LEAD (SUM(TOTAL),1) OVER (ORDER BY TRUNC(DATA)) posterior
FROM TCONTRATO
GROUP BY TRUNC(DATA)
ORDER BY TRUNC(DATA);



SELECT * FROM TCONTRATO;



