CREATE OR REPLACE VIEW V_ALUNO
AS
  SELECT COD_ALUNO AS CODIGO, SALARIO, ESTADO,
         NOME AS ALUNO, CIDADE
  FROM TALUNO
  WHERE ESTADO = 'RS';
  
SELECT * FROM V_ALUNO
ORDER BY ALUNO;

CREATE OR REPLACE VIEW V_CONTRATO_TOP
AS
  SELECT COD_CONTRATO, DESCONTO
  FROM TCONTRATO
  WHERE DESCONTO >= 10;
  
SELECT * FROM V_CONTRATO_TOP;

SELECT VIEW_NAME, TEXT
FROM USER_VIEWS;

CREATE OR REPLACE VIEW V_ALUNO2(COD, ALUNO, SAL)
AS
  SELECT COD_ALUNO, NOME, SALARIO
  FROM TALUNO;
 
SELECT * FROM V_ALUNO2;

CREATE OR REPLACE VIEW V_CONTRATO
AS
  SELECT TRUNC(DATA) AS DATA,
         MAX(DESCONTO) MAXIMO,
         AVG(DESCONTO) MEDIA,
         COUNT(*) QTDE
  FROM TCONTRATO
  GROUP BY TRUNC(DATA);
  
SELECT * FROM V_CONTRATO;

CREATE OR REPLACE VIEW V_PESSOA_F
AS
  SELECT COD_PESSOA, TIPO, NOME, COD_RUA AS RUA
  FROM TPESSOACURSO
  WHERE TIPO='F';
  
SELECT * FROM V_PESSOA_F;

SELECT PES.COD_PESSOA AS CODIGO,
       PES.NOME AS PESSOA,
       CID.NOME AS CIDADE,
       RUA.NOME AS RUA
FROM V_PESSOA_F PES, TRUACURSO RUA, TCIDADECURSO CID
WHERE PES.RUA = RUA.COD_RUA (+)
AND CID.COD_CIDADE = RUA.COD_CIDADE
ORDER BY PES.NOME;

CREATE OR REPLACE VIEW VCURSOS1000CK
AS
  SELECT COD_CURSO, NOME, VALOR
  FROM TCURSO
  WHERE VALOR = 1000
  WITH CHECK OPTION CONSTRAINT VCURSPS1000_CK;
  
INSERT INTO VCURSOS1000CK
         (COD_CURSO, NOME, VALOR)
VALUES   (52, 'TESTE Y', 1000);

SELECT * FROM TCURSO;

SELECT * FROM V_ALUNO;

DELETE FROM V_ALUNO WHERE CODIGO = 3;

INSERT INTO V_ALUNO
VALUES (50, 500, 'SP', 'MARIA', 'NH');

COMMIT;

DELETE FROM V_CONTRATO;

CREATE OR REPLACE VIEW V_ALUNO3
AS
  SELECT COD_ALUNO CODIGO, 
         NOME ALUNO, CIDADE
  FROM TALUNO
  WHERE ESTADO = 'RS'
  WITH READ ONLY;
  
DELETE FROM V_ALUNO3;

DROP VIEW V_ALUNO3;




