SELECT COD_CONTRATO, DATA, TOTAL
FROM TCONTRATO
WHERE TOTAL >=
  ( SELECT VALOR FROM TCURSO
    WHERE COD_CURSO = 3 );
    
SELECT * FROM TALUNO;

SELECT COD_ALUNO, NOME, CIDADE
FROM TALUNO
WHERE (CIDADE, ESTADO) = 
          ( SELECT CIDADE, ESTADO FROM TALUNO
            WHERE COD_ALUNO = 1 )
AND COD_ALUNO <> 1;

SELECT COD_CURSO, MIN(VALOR), SUM(VALOR),
       COUNT(*) QTDE
FROM TITEM
WHERE COD_CURSO > 0
GROUP BY COD_CURSO
HAVING MIN(VALOR) >=
       (SELECT AVG(VALOR) FROM TCURSO)
ORDER BY COD_CURSO;

SELECT AVG(VALOR) FROM TCURSO;

SELECT COD_ALUNO, MIN(TOTAL), SUM(TOTAL)
FROM TCONTRATO
GROUP BY COD_ALUNO
HAVING MIN(TOTAL) >
   (SELECT AVG(VALOR) FROM TCURSO);
   
SELECT COD_CURSO, NOME, VALOR
FROM TCURSO
WHERE COD_CURSO IN (SELECT COD_CURSO FROM TITEM);
