CREATE TABLE TESTECURSO
(
  CODIGO NUMBER NOT NULL PRIMARY KEY,
  DATA DATE DEFAULT SYSDATE
);

DESC TESTECURSO;

INSERT INTO TESTECURSO (CODIGO) VALUES (1);

INSERT INTO TESTECURSO (CODIGO, DATA) VALUES (2, '03/08/2013');

SELECT * FROM TESTECURSO;

SELECT * FROM USER_TABLES;

SELECT * FROM ALL_TABLES;

CREATE TABLE TCONTRATO_VIP
AS
 SELECT * FROM TCONTRATO WHERE TOTAL > 500;
 
SELECT * FROM TCONTRATO_VIP;

ALTER TABLE TCONTRATO_VIP ADD VALOR NUMBER(5, 2);

ALTER TABLE TCONTRATO_VIP MODIFY VALOR NUMBER(8, 2);

ALTER TABLE TCONTRATO_VIP MODIFY VALOR NUMBER(12, 2) DEFAULT 0;

ALTER TABLE TCONTRATO_VIP RENAME COLUMN VALOR TO VALOR2;

ALTER TABLE TCONTRATO_VIP DROP COLUMN VALOR2;

SELECT * FROM TCONTRATO_VIP;

DROP TABLE TCONTRATO_VIP;

RENAME TCONTRATO TO TCONTRATO_TOP;

SELECT * FROM TCONTRATO_TOP;

RENAME TCONTRATO_TOP TO TCONTRATO;

SELECT * FROM TCONTRATO;

COMMENT ON TABLE TCONTRATO IS 'Tabela criada para uso no curso de banco de dados Oracle';

COMMENT ON COLUMN TCONTRATO.COD_CONTRATO IS 'Código do Contrato';

COMMENT ON COLUMN TCONTRATO.DATA IS 'Data de emissão do contrato';

SELECT * FROM USER_COL_COMMENTS WHERE TABLE_NAME='TCONTRATO';

SELECT * FROM USER_TAB_COMMENTS WHERE TABLE_NAME='TCONTRATO';

ALTER TABLE TCONTRATO ADD TOTAL2 NUMBER(8, 2);

ALTER TABLE TCONTRATO SET UNUSED(TOTAL2);

SELECT * FROM TCONTRATO;

ALTER TABLE TCONTRATO DROP UNUSED COLUMNS;
